AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local test version of the profile microservice.

Resources:

    DeviceService:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
            Timeout: 300
            Environment:
                Variables:
                    SETTINGS_TBL: TMP
                    DEVICE_TYPES_TBL: TMP
                    DEVICES_TBL: TMP
                    LOGGING_LEVEL: TMP
                    SIMULATOR_QUEUE: TMP
            Events:
                DeviceTypes:
                    Type: Api
                    Properties:
                        Path: /devices/types
                        Method: ANY
                DeviceType:
                    Type: Api
                    Properties:
                        Path: /devices/types/{typeid}
                        Method: ANY
                DeviceWidgets:
                    Type: Api
                    Properties:
                        Path: /devices/widgets
                        Method: ANY
                DeviceWidget:
                    Type: Api
                    Properties:
                        Path: /devices/widgets/{deviceid}
                        Method: ANY
