AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local test version of the metrics microservice.

Resources:

    MetricsService:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs6.10
            Timeout: 300
            Environment:
                Variables:
                    SETTINGS_TBL: TMP
                    LOGGING_LEVEL: TMP
                    METRICS_TBL: TMP
            Events:
                GetMetrics:
                    Type: Api
                    Properties:
                        Path: /metrics
                        Method: ANY
